### PR TITLE
Add: Information about image registries, artifact management and rela…

### PR DESCRIPTION
**Pull request by rossbachp**
Hello Ivan,

after our insightful discussion yesterday on container runtimes, I'm excited to share with you information about various registry projects. I've compiled some details from your image tooling chapter, so please excuse any duplications.

Life with happiness and yesterday was the happy earth day...
Peter

### CODE REVIEW

**Comment by iximiuz** [comment]
What a great contribution! Thanks a lot, @rossbachp! Merging momentarily 🚀

**Comment by rossbachp** [comment]
Many thanks!

**Comment by rossbachp** [comment]
I believe it was beneficial to include the new chapter in the README.md index:)

**Comment by iximiuz** [comment]
Great idea! The `./DISTRIBUTIONS.md` link is now included in the README file.

**Pull request merged**
